// <auto-generated />
using System;
using ChaQaQcLabApi.Infrastructure.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChaQaQcLabApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ChaQaQcLabApi.Domain.Models.CurlingForce.CurlingForceTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("varchar(40)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("TestPurpose")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ProductId");

                    b.ToTable("CurlingForceTests");
                });

            modelBuilder.Entity("ChaQaQcLabApi.Domain.Models.ForcedClose.ForcedCloseTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("varchar(40)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("TestPurpose")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ProductId");

                    b.ToTable("ForcedCloseTests");
                });

            modelBuilder.Entity("ChaQaQcLabApi.Domain.Models.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Products");
                });

            modelBuilder.Entity("ChaQaQcLabApi.Domain.Models.Rock.RockTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("varchar(40)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("TestPurpose")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ProductId");

                    b.ToTable("RockTests");
                });

            modelBuilder.Entity("ChaQaQcLabApi.Domain.Models.SoftClose.SoftCloseTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("varchar(40)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("TestPurpose")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ProductId");

                    b.ToTable("SoftCloseTests");
                });

            modelBuilder.Entity("ChaQaQcLabApi.Domain.Models.StaticLoad.StaticLoadTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("varchar(40)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("TestPurpose")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ProductId");

                    b.ToTable("StaticLoadTests");
                });

            modelBuilder.Entity("ChaQaQcLabApi.Domain.Models.Tester", b =>
                {
                    b.Property<string>("EmployeeId")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.HasKey("EmployeeId");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.ToTable("Testers");
                });

            modelBuilder.Entity("ChaQaQcLabApi.Domain.Models.WaterProofing.WaterProofingTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("varchar(40)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("TestPurpose")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ProductId");

                    b.ToTable("WaterProofingTests");
                });

            modelBuilder.Entity("ChaQaQcLabApi.Domain.Models.CurlingForce.CurlingForceTest", b =>
                {
                    b.HasOne("ChaQaQcLabApi.Domain.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("ChaQaQcLabApi.Domain.Models.CurlingForce.CurlingForceTestSample", "Samples", b1 =>
                        {
                            b1.Property<int>("CurlingForceTestId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            b1.Property<double>("DeformationDegree")
                                .HasColumnType("double");

                            b1.Property<int>("Duration")
                                .HasColumnType("int");

                            b1.Property<string>("EmployeeId")
                                .IsRequired()
                                .HasColumnType("varchar(20)");

                            b1.Property<double>("Load")
                                .HasColumnType("double");

                            b1.Property<string>("Note")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<int>("NumberOfError")
                                .HasColumnType("int");

                            b1.HasKey("CurlingForceTestId", "Id");

                            b1.HasIndex("EmployeeId");

                            b1.ToTable("CurlingForceTestSamples");

                            b1.WithOwner()
                                .HasForeignKey("CurlingForceTestId");

                            b1.HasOne("ChaQaQcLabApi.Domain.Models.Tester", "Tester")
                                .WithMany()
                                .HasForeignKey("EmployeeId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.Navigation("Tester");
                        });

                    b.Navigation("Product");

                    b.Navigation("Samples");
                });

            modelBuilder.Entity("ChaQaQcLabApi.Domain.Models.ForcedClose.ForcedCloseTest", b =>
                {
                    b.HasOne("ChaQaQcLabApi.Domain.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("ChaQaQcLabApi.Domain.Models.ForcedClose.ForcedCloseTestSample", "Samples", b1 =>
                        {
                            b1.Property<int>("ForcedCloseTestId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            b1.Property<string>("EmployeeId")
                                .IsRequired()
                                .HasColumnType("varchar(20)");

                            b1.Property<string>("Note")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<int>("NumberOfClosing")
                                .HasColumnType("int");

                            b1.Property<int>("NumberOfError")
                                .HasColumnType("int");

                            b1.HasKey("ForcedCloseTestId", "Id");

                            b1.HasIndex("EmployeeId");

                            b1.ToTable("ForcedCloseTestSamples");

                            b1.HasOne("ChaQaQcLabApi.Domain.Models.Tester", "Tester")
                                .WithMany()
                                .HasForeignKey("EmployeeId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("ForcedCloseTestId");

                            b1.OwnsOne("ChaQaQcLabApi.Domain.Models.ForcedClose.ForcedCloseTestSampleResult", "SeatLidResult", b2 =>
                                {
                                    b2.Property<int>("ForcedCloseTestSampleForcedCloseTestId")
                                        .HasColumnType("int");

                                    b2.Property<int>("ForcedCloseTestSampleId")
                                        .HasColumnType("int");

                                    b2.Property<int>("FallTime")
                                        .HasColumnType("int");

                                    b2.Property<bool>("IsIntact")
                                        .HasColumnType("tinyint(1)");

                                    b2.Property<bool>("IsUnleaked")
                                        .HasColumnType("tinyint(1)");

                                    b2.Property<bool>("Passed")
                                        .HasColumnType("tinyint(1)");

                                    b2.HasKey("ForcedCloseTestSampleForcedCloseTestId", "ForcedCloseTestSampleId");

                                    b2.ToTable("ForcedCloseTestSamples");

                                    b2.WithOwner()
                                        .HasForeignKey("ForcedCloseTestSampleForcedCloseTestId", "ForcedCloseTestSampleId");
                                });

                            b1.OwnsOne("ChaQaQcLabApi.Domain.Models.ForcedClose.ForcedCloseTestSampleResult", "SeatRingResult", b2 =>
                                {
                                    b2.Property<int>("ForcedCloseTestSampleForcedCloseTestId")
                                        .HasColumnType("int");

                                    b2.Property<int>("ForcedCloseTestSampleId")
                                        .HasColumnType("int");

                                    b2.Property<int>("FallTime")
                                        .HasColumnType("int");

                                    b2.Property<bool>("IsIntact")
                                        .HasColumnType("tinyint(1)");

                                    b2.Property<bool>("IsUnleaked")
                                        .HasColumnType("tinyint(1)");

                                    b2.Property<bool>("Passed")
                                        .HasColumnType("tinyint(1)");

                                    b2.HasKey("ForcedCloseTestSampleForcedCloseTestId", "ForcedCloseTestSampleId");

                                    b2.ToTable("ForcedCloseTestSamples");

                                    b2.WithOwner()
                                        .HasForeignKey("ForcedCloseTestSampleForcedCloseTestId", "ForcedCloseTestSampleId");
                                });

                            b1.Navigation("SeatLidResult")
                                .IsRequired();

                            b1.Navigation("SeatRingResult")
                                .IsRequired();

                            b1.Navigation("Tester");
                        });

                    b.Navigation("Product");

                    b.Navigation("Samples");
                });

            modelBuilder.Entity("ChaQaQcLabApi.Domain.Models.Rock.RockTest", b =>
                {
                    b.HasOne("ChaQaQcLabApi.Domain.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("ChaQaQcLabApi.Domain.Models.Rock.RockTestSample", "Samples", b1 =>
                        {
                            b1.Property<int>("RockTestId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            b1.Property<string>("EmployeeId")
                                .IsRequired()
                                .HasColumnType("varchar(20)");

                            b1.Property<double>("Load")
                                .HasColumnType("double");

                            b1.Property<string>("Note")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<int>("NumberOfError")
                                .HasColumnType("int");

                            b1.Property<bool>("Passed")
                                .HasColumnType("tinyint(1)");

                            b1.Property<int>("TestedTimes")
                                .HasColumnType("int");

                            b1.HasKey("RockTestId", "Id");

                            b1.HasIndex("EmployeeId");

                            b1.ToTable("RockTestSamples");

                            b1.HasOne("ChaQaQcLabApi.Domain.Models.Tester", "Tester")
                                .WithMany()
                                .HasForeignKey("EmployeeId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("RockTestId");

                            b1.Navigation("Tester");
                        });

                    b.Navigation("Product");

                    b.Navigation("Samples");
                });

            modelBuilder.Entity("ChaQaQcLabApi.Domain.Models.SoftClose.SoftCloseTest", b =>
                {
                    b.HasOne("ChaQaQcLabApi.Domain.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("ChaQaQcLabApi.Domain.Models.SoftClose.SoftCloseTestSample", "Samples", b1 =>
                        {
                            b1.Property<int>("SoftCloseTestId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            b1.Property<string>("EmployeeId")
                                .IsRequired()
                                .HasColumnType("varchar(20)");

                            b1.Property<string>("Note")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<int>("NumberOfClosing")
                                .HasColumnType("int");

                            b1.Property<int>("NumberOfError")
                                .HasColumnType("int");

                            b1.HasKey("SoftCloseTestId", "Id");

                            b1.HasIndex("EmployeeId");

                            b1.ToTable("SoftCloseTestSamples");

                            b1.HasOne("ChaQaQcLabApi.Domain.Models.Tester", "Tester")
                                .WithMany()
                                .HasForeignKey("EmployeeId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("SoftCloseTestId");

                            b1.OwnsOne("ChaQaQcLabApi.Domain.Models.SoftClose.SoftCloseTestSampleResult", "SeatLidResult", b2 =>
                                {
                                    b2.Property<int>("SoftCloseTestSampleSoftCloseTestId")
                                        .HasColumnType("int");

                                    b2.Property<int>("SoftCloseTestSampleId")
                                        .HasColumnType("int");

                                    b2.Property<int>("FallTime")
                                        .HasColumnType("int");

                                    b2.Property<bool>("IsBumperIntact")
                                        .HasColumnType("tinyint(1)");

                                    b2.Property<bool>("IsUnleaked")
                                        .HasColumnType("tinyint(1)");

                                    b2.Property<bool>("Passed")
                                        .HasColumnType("tinyint(1)");

                                    b2.HasKey("SoftCloseTestSampleSoftCloseTestId", "SoftCloseTestSampleId");

                                    b2.ToTable("SoftCloseTestSamples");

                                    b2.WithOwner()
                                        .HasForeignKey("SoftCloseTestSampleSoftCloseTestId", "SoftCloseTestSampleId");
                                });

                            b1.OwnsOne("ChaQaQcLabApi.Domain.Models.SoftClose.SoftCloseTestSampleResult", "SeatRingResult", b2 =>
                                {
                                    b2.Property<int>("SoftCloseTestSampleSoftCloseTestId")
                                        .HasColumnType("int");

                                    b2.Property<int>("SoftCloseTestSampleId")
                                        .HasColumnType("int");

                                    b2.Property<int>("FallTime")
                                        .HasColumnType("int");

                                    b2.Property<bool>("IsBumperIntact")
                                        .HasColumnType("tinyint(1)");

                                    b2.Property<bool>("IsUnleaked")
                                        .HasColumnType("tinyint(1)");

                                    b2.Property<bool>("Passed")
                                        .HasColumnType("tinyint(1)");

                                    b2.HasKey("SoftCloseTestSampleSoftCloseTestId", "SoftCloseTestSampleId");

                                    b2.ToTable("SoftCloseTestSamples");

                                    b2.WithOwner()
                                        .HasForeignKey("SoftCloseTestSampleSoftCloseTestId", "SoftCloseTestSampleId");
                                });

                            b1.Navigation("SeatLidResult")
                                .IsRequired();

                            b1.Navigation("SeatRingResult")
                                .IsRequired();

                            b1.Navigation("Tester");
                        });

                    b.Navigation("Product");

                    b.Navigation("Samples");
                });

            modelBuilder.Entity("ChaQaQcLabApi.Domain.Models.StaticLoad.StaticLoadTest", b =>
                {
                    b.HasOne("ChaQaQcLabApi.Domain.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("ChaQaQcLabApi.Domain.Models.StaticLoad.StaticLoadTestSample", "Samples", b1 =>
                        {
                            b1.Property<int>("StaticLoadTestId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            b1.Property<string>("EmployeeId")
                                .IsRequired()
                                .HasColumnType("varchar(20)");

                            b1.Property<string>("Note")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<int>("NumberOfError")
                                .HasColumnType("int");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.HasKey("StaticLoadTestId", "Id");

                            b1.HasIndex("EmployeeId");

                            b1.ToTable("StaticLoadTestSamples");

                            b1.HasOne("ChaQaQcLabApi.Domain.Models.Tester", "Tester")
                                .WithMany()
                                .HasForeignKey("EmployeeId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("StaticLoadTestId");

                            b1.Navigation("Tester");
                        });

                    b.Navigation("Product");

                    b.Navigation("Samples");
                });

            modelBuilder.Entity("ChaQaQcLabApi.Domain.Models.WaterProofing.WaterProofingTest", b =>
                {
                    b.HasOne("ChaQaQcLabApi.Domain.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("ChaQaQcLabApi.Domain.Models.WaterProofing.WaterProofingTestSample", "Samples", b1 =>
                        {
                            b1.Property<int>("WaterProofingTestId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            b1.Property<int>("Duration")
                                .HasColumnType("int");

                            b1.Property<string>("EmployeeId")
                                .IsRequired()
                                .HasColumnType("varchar(20)");

                            b1.Property<string>("Note")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<int>("NumberOfError")
                                .HasColumnType("int");

                            b1.Property<bool>("Passed")
                                .HasColumnType("tinyint(1)");

                            b1.Property<double>("Temperature")
                                .HasColumnType("double");

                            b1.HasKey("WaterProofingTestId", "Id");

                            b1.HasIndex("EmployeeId");

                            b1.ToTable("WaterProofingTestSamples");

                            b1.HasOne("ChaQaQcLabApi.Domain.Models.Tester", "Tester")
                                .WithMany()
                                .HasForeignKey("EmployeeId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("WaterProofingTestId");

                            b1.Navigation("Tester");
                        });

                    b.Navigation("Product");

                    b.Navigation("Samples");
                });
#pragma warning restore 612, 618
        }
    }
}
